import {
  app,
  type HttpRequest,
  type InvocationContext,
  type HttpResponse,
} from "@azure/functions/src/index.js";

const fetchDefinition = async (query: string, groqKey: string) => {
  if (!query.startsWith("define ")) return "";

  const word = query.replace("define ", "");

  const wiktionaryResponse = await fetch(
    `https://simple.wiktionary.org/w/api.php?action=query&prop=revisions&rvprop=content&format=json&titles=${word}`,
  );
  if (!wiktionaryResponse.ok) {
    console.warn("Failed to fetch wiktionary definition", wiktionaryResponse.statusText);
    return "";
  }
  const wiktionaryData: { query: { pages: Record<string, { revisions?: [{ "*": string }] }> } } =
    await wiktionaryResponse.json();

  const page = Object.values(wiktionaryData.query.pages)[0];
  if (!page.revisions) {
    console.warn("Failed to fetch wiktionary definition", page);
    return "";
  }
  const content = page.revisions[0]["*"];

  const groqResponse = await fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${groqKey}`,
    },
    body: JSON.stringify({
      messages: [
        {
          role: "user",
          content: `<attachment>${content}</attachment>\nDefine ${word} in one sentence using only simple, common language.`,
        },
      ],
      model: "llama-3.2-3b-preview",
      temperature: 0,
    }),
  });
  if (!groqResponse.ok) {
    console.warn("Failed to use Groq", groqResponse.statusText);
    return "";
  }
  const groqData = await groqResponse.json();

  const definition = groqData.choices[0].message.content.trim();

  return definition;
};

const checkBlocked = (url: string) => {
  const whitelist = [
    "*.airast.org*",
    "*.cloud1.tds.airast.org",
    "*.cloud2.tds.airast.org",
    "*.dictionaryapi.com*",
    "*.googleapis.com*",
    "*.merriam-webster.com*",
    "*.tds.airast.org",
    "production.classviewapi.com*",
    "13.33.151-Airast",
    "161.47.84-Airast",
    "161.47.84.104-airast.org",
    "161.47.84.120-airast.org",
    "161.47.84.128-airast.org",
    "161.47.84.136-airast.org",
    "161.47.84.144-airast.org",
    "161.47.84.200-airast.org",
    "161.47.84.208-airast.org",
    "161.47.84.217-airast.org",
    "161.47.84.228-airast.org",
    "161.47.84.232-airast.org",
    "161.47.84.32-airast.org",
    "161.47.84.40-airast.org",
    "161.47.84.48-airast.org",
    "161.47.84.56-airast.org",
    "161.47.84.64-airast.org",
    "161.47.84.72-airast.org",
    "166.78-SBAC",
    "184.106.100.135-SBAC",
    "192.237.154-SBAC",
    "198.61.245-SBAC",
    "64.124.231.250-Dictionary",
    "67.192.42-Airast",
    "clients1.google.com",
    "clients2.google.com",
    "clients3.google.com",
    "clients4.google.com",
    "clientservices.googleapis.com",
    "maac.sso.airast.org",
    "maac.tide.airast.org",
    "media.merriam-webster.com",
    "ocsp.geotrust.com",
    "ocsp.thawte.com",
    "ocsp.ws.symantec.com",
    "tools.google.com",
    "update.googleapis.com",
    "wa.portal.airast.org",
    "wa.reports.airast.org",
    "wa.tss.airast.org",
    "www.dictionaryapi.com",
    "www.googleapis.com",
    "www.gstatic.com",
    "https://sso1.airast.org/auth/realms/washington/account",
    "wa.tide.arast.org",
    "https://wa.reports.airast.org/",
    "*.geotrust.com",
    "*.thawte.com",
    "*.ws.symantec.com",
    "http://hangouts.google.com/",
    "*wikipedia.org*",
    "*translate.google.com*",
    "*alamy.com*",
    "*www.accessible-archives.com/*",
    "*https://vimeo.com/357620460*",
    "*https://mrbergeronhistory.files.wordpress.com/*",
    "login10.cloud1.tds.airast.org",
    "sites.google.com/apps.nsd.org/*",
    "*.seesaw.me*",
    "127.0.0.1",
    "*localhost*",
    "*.squarespace.com*",
    "*.jquery.com*",
    "*.wistia.com*",
    "*.squarespace-cdn.com*",
    "*.app-measurement.com*",
    "*.typekit.net",
    "https://player.vimeo.com/video/190333454",
    "*.zoom.us*",
    "*classroom.google.com*",
    "*drive.google.com*",
    "*docs.google.com*",
    "*viewpure.com*",
    "*www.viewpure.com*",
    "https://www.huffpost.com/entry/sorry-teachers-but-my-sleep-is-more-important-than-homework_b_7075242",
    "*sites.google.com/view/ms-catlyns-classroom/*",
    "http://gavdoy.com/",
    "*rhino3du.ning.com/*",
    "https://player.vimeo.com/video/96651591",
    "https://player.vimeo.com/video/96645374",
    "https://player.vimeo.com/video/95545448",
    "*.tofugu.com*",
    "https://vimeo.com/369662005",
    "https://vimeo.com/369616557",
    "https://vimeo.com/369662488",
    "https://vimeo.com/369663016",
    "https://vimeo.com/369663459",
    "https://vimeo.com/369664240",
    "embed-cdn.ziggeo.com",
    "social.uploadcare.com",
    "*www.vintageadbrowser.com/*",
    "*mobile.hotspot/*",
    "http://192.168.0.1/",
    "https://vimeo.com/showcase/6880106",
    "https://www.youtube.com/watch?v=Di1oLS16WvA&feature=youtu.be",
    "*sites.google.com/view/kclsbothellkenmoresrp/*",
    "*vtuos.pub*",
    "http://vtuos.pub*",
    "*.donjohnston.net*",
    "https://www.yogajournal.com/*",
    "*safeshare.*",
    "sites.google.com/view/kclsnorthshoremocknewbery20-21/*",
    "*sites.google.com/view/kclsnorthshoremocknewbery20-21/*",
    "*www.youtube-nocookie.com*",
    "*i.ytimg.com*",
    "*www.google-analytics.com*",
    "*ajax.googleapis.com*",
    "*api.qrserver.com*",
    "*chart.googleapis.com*",
    "*yt3.ggpht.com*",
    "*fonts.gstatic.com*",
    "*static.addtoany.com*",
    "*hundreds-chart-game.com*",
    "*skribbl.io/*",
    "*.chromiumapp.org*",
    "https://vimeo.com/event/396632",
    "wss://eastus.stt.speech.microsoft.com/",
    "*.pearsontestcontent.com:80*",
    "*.pearsontestcontent.com:443*",
    "*.testnav.com:80*",
    "*.testnav.com:443*",
    "flowvella.com",
    "https://www.dailymotion.com/video/x6ci2hk",
    "https://player.vimeo.com/video/480506132",
    "https://player.vimeo.com/video/480516076",
    "https://player.vimeo.com/video/480522459",
    "https://player.vimeo.com/video/178419379?dnt=1&app_id=122963",
    "https://player.vimeo.com/video/178419383?dnt=1&app_id=122963",
    "https://player.vimeo.com/video/212092746?dnt=1&app_id=122963",
    "https://vimeo.com/196028052/66d61ee86b",
    "https://vimeo.com/97616198",
    "https://www.esquire.com/entertainment/a33010679/who-is-marsha-p-johnson-pride-2020-essay/",
    "https://community.foodrevolution.org/products/tntg-impactkit/film",
    "https://vimeo.com/548074118",
    "c328740.ssl.cf1.rackcdn.com",
    "cdn.mathjax.org",
    "sbdasset.evo-text.com/",
    "desmos.com/ § use.typekit.net/",
    "p.typekit.net/ § d2ix43re9fm3y5.cloudfront.net",
    "items.learnosity.com § player.vimeo.com/",
    "wiris.com",
    "games.zinclearninglabs.com",
    "*.springboardonline.org",
    "https://elearning.heart.org/scorm/launchsco/26671659/1365",
    "https://netbeans.apache.org/*",
    "http://nutanixframe.com",
    "https://slack.com/",
    "*ggpht.com*",
    "https://bonesdontlie.wordpress.com/2013/04/09/can-you-determine-activity-from-human-remains/*",
    "https://console.nutanix.com/",
    "console.nutanix.com",
    "*.console.nutanix.com",
    "http://download.eclipse.org",
    "*.download.eclipse.org",
    "*.platform.techsmart.codes",
    "*.replitusercontent.com*",
    "http://replitusercontent.com",
    "*remotedesktop.google.com*",
    "https://medium.com/equality-includes-you/what-white-people-can-do-for-racial-justice-f2d18b0e0234",
    "*nutanix.com*",
    "https://www.google.com:443/speech-api/*",
    "wss://*.amira.services:443",
    "*studio.balfour.com*",
    "*nutanixframe.com*",
    "*loggly.com*",
    "*js.hs-banner.com*",
    "*js.hs-analytics.net*",
    "*js-agent.newrelic.com*",
    "*crazyegg.com*",
    "nccs-grader.herokuapp.com/*",
    "http://*.texthelp.com",
    "http://*.googleapis.com",
    "https://sdzsafaripark.org/cams/tiger-cam",
    "http://www.software3d.com/Home/Vax/Immunity.php",
    "https://vimeo.com/457914639",
    "*cdn.bfldr.com/*",
    "https://*.amira.services*",
    "https://janeaustensworld.com/social-customs-and-the-regency-world/",
    "http://cosmosandcrayons.blogspot.com/2013/06/science-facts-thursday-solar-system.html",
    "https://sso.amira.services/tool*",
    "*.amira.services:443",
    "https://sentry.io:443",
    "https://www.amiratutor.com:443",
    "https://api.getmagicbox.com",
    "https://*.cloudfront.net:443",
    "https://*.amazonaws.com:443",
    "wss://*.amira.services:443*",
    "https://*wss://*.amira.services:443*",
    "http://*wss://*.amira.services:443*",
    "https://wss://*.amira.services:443*",
    "http://wss://*.amira.services:443*",
    "*amira.services*",
    "*learnasl.dawnsigndigital.com/*",
    "*articulateusercontent.com*",
    "*articulate.com*",
    "https://miro.com/app/board/o9J_lWn3HfA=/?moveToWidget=3074457355051807331&cot=14",
    "https://docs.google.com/presentation/d/e/2PACX-1vREUk0LH95w52-6V5dQov08iIACp6mSDjp1nT7_iDsOg0jQD9v_fH9yszlCCAvsvoxKdCy7BdRlqfpq/pub?start=false&loop=false&delayms=3000&slide=id.gbc7a72a55d_0_3",
    "ocsp.apple.com",
    "apps.mzstatic.com",
    "updates.cdn-apple.com",
    "https://vimeo.com/100453588",
    "https://zapatopi.net/*",
    "https://nofilmschool.com/must-know-camera-movements",
    "https://blog.storyblocks.com/video-tutorials/7-basic-camera-movements/",
    "http://seattlechannel.org/videos?videoid=x83623",
    "*xceleratedriving.com*",
    "https://streamyard.com/p2us8vqhca",
    "stax-socket-production.herokuapp.com",
    "*api.us-east-1.amazonaws.com*",
    "*bomgarcloud.com*",
    "*jamf.com*",
    "*jamf.connect.com*",
    "*jamfcloud.com*",
    "*comf.jamf.connect.login*",
    "*azurewebsites.net*",
    "*g.live.com*",
    "*msftauth.net*",
    "*microsoftonline.com*",
    "*incidentiq.com*",
    "https://cottontrade.herokuapp.com/*",
    "https://remote.nsd.org:8443",
    "minecraftprod.rtep.msgamestudios.com",
    "www.xboxab.com",
    "login.minecrafteduservices.com",
    "client.discovery.minecraft-services.net",
    "da.xboxservices.com",
    "downloads.minecrafteduservices.com",
    "http://meedownloads.blob.core.windows.net/*",
    "https://contentstorage.onenote.office.net/*",
    "https://meedownloads.azureedge.net/*",
    "https://minecraft.makecode.com/*",
    "https://makecode.com/*",
    "https://trg-minecraft.userpxt.io/*",
    "https://www.youtube.com/watch?v=2ydHL5wkmJo",
    "https://www.washingtontribes.org/the-tribes-of-washington/",
    "https://923948.smushcdn.com/2358878/wp-content/uploads/*",
    "*neverssl.com*",
    "newassets.hcaptcha.com",
    "store.mktpl.minecraft‑services.net",
    "*.minecrafteduservices.com",
    "*.minecraft-services.net",
    "*.xboxlive.com",
    "*.playfabapi.com",
    "education.minecraft.net",
    "self.events.data.microsoft.com",
    "meedownloads.blob.core.windows.net",
    "contentstorage.onenote.office.net",
    "meedownloads.azureedge.net",
    "cognitiveservices.azure.com",
    "learningtools.onenote.com",
    "minecraft.makecode.com",
    "makecode.com",
    "trg-minecraft.userpxt.io",
    "pxt.azureedge.net",
    "api.github.com",
    "www.tynker.com",
    "kodable-web.herokuapp.com",
    "player.vimeo.com/video/510413496",
    "https://vimeo.com/510413496",
    "https://vimeo.com/178418492",
    "https://vimeo.com/178419225",
    "https://vimeo.com/178418497",
    "https://vimeo.com/178419226",
    "https://vimeo.com/178424957",
    "https://vimeo.com/178419363",
    "https://vimeo.com/178419223",
    "https://vimeo.com/178418496",
    "https://vimeo.com/178419228",
    "https://vimeo.com/119653413",
    "https://vimeo.com/578565190",
    "https://vimeo.com/178419217",
    "https://vimeo.com/178419367",
    "https://vimeo.com/178419369",
    "https://vimeo.com/178419365",
    "https://vimeo.com/178424593",
    "https://vimeo.com/119385779",
    "https://vimeo.com/178424859",
    "https://vimeo.com/220021231",
    "https://vimeo.com/119386615",
    "https://vimeo.com/625705859",
    "https://vimeo.com/118850606",
    "https://vimeo.com/597413316",
    "https://vimeo.com/599516321",
    "https://vimeo.com/597413022",
    "https://vimeo.com/119386258",
    "https://vimeo.com/119386616",
    "https://vimeo.com/178424847",
    "https://vimeo.com/119385778",
    "https://vimeo.com/597413726",
    "https://vimeo.com/178424952",
    "https://vimeo.com/178418494",
    "https://vimeo.com/178418493",
    "https://vimeo.com/178424856",
    "https://vimeo.com/597413699",
    "https://vimeo.com/597413635",
    "https://vimeo.com/119386260",
    "https://vimeo.com/178424587",
    "https://vimeo.com/119386618",
    "https://vimeo.com/597413477",
    "https://vimeo.com/119653414",
    "https://vimeo.com/597414018",
    "https://vimeo.com/178424958",
    "https://vimeo.com/597413271",
    "https://vimeo.com/178424954",
    "https://vimeo.com/178419376",
    "https://vimeo.com/178419377",
    "https://vimeo.com/178419378",
    "https://vimeo.com/119386617",
    "https://vimeo.com/119386259",
    "https://vimeo.com/578566194",
    "https://vimeo.com/256833051",
    "https://vimeo.com/597413379",
    "https://vimeo.com/410338882",
    "https://vimeo.com/178419063",
    "https://vimeo.com/215515045",
    "https://vimeo.com/219117189",
    "https://vimeo.com/219117170",
    "https://vimeo.com/178424588",
    "https://vimeo.com/178424591",
    "https://vimeo.com/578564546",
    "https://vimeo.com/625705799",
    "https://vimeo.com/625705307",
    "https://vimeo.com/212097702",
    "https://vimeo.com/178424469",
    "https://vimeo.com/625705629",
    "https://vimeo.com/212095847",
    "https://vimeo.com/164108680",
    "https://vimeo.com/652603933",
    "https://vimeo.com/212094339",
    "https://vimeo.com/578564287",
    "https://vimeo.com/578564421",
    "https://vimeo.com/578564501",
    "https://vimeo.com/652987899",
    "https://vimeo.com/652988182",
    "https://vimeo.com/652987978",
    "https://vimeo.com/178424800",
    "https://vimeo.com/178419333",
    "https://vimeo.com/454424639",
    "https://vimeo.com/178419178",
    "https://vimeo.com/178424447",
    "https://vimeo.com/179955774",
    "https://vimeo.com/179955776",
    "https://vimeo.com/178419138",
    "https://vimeo.com/454424482",
    "https://vimeo.com/454424818",
    "https://vimeo.com/454424715",
    "https://vimeo.com/454425013",
    "https://vimeo.com/670849701",
    "https://vimeo.com/625705690",
    "https://vimeo.com/178419385",
    "https://vimeo.com/178419383",
    "https://vimeo.com/652603789",
    "https://vimeo.com/652603977",
    "https://vimeo.com/652604064",
    "https://vimeo.com/178424782",
    "https://vimeo.com/178424790",
    "https://vimeo.com/89513664",
    "https://vimeo.com/652604154",
    "https://vimeo.com/652604267",
    "https://vimeo.com/215515027",
    "https://vimeo.com/652988301",
    "https://vimeo.com/652988226",
    "https://vimeo.com/652988302",
    "10.10.10.1",
    "img.itch.zone/aW1nLzkxMD*",
    "img.itch.zone/aW1hZ2UvMTU1OTk0OS85MTA0OT*",
    "*aW1hZ2UvMTU1OTk0OS85MTA0OT*",
    "*aW1nLzkxMD*",
    "*static.itch.io*",
    "https://youtu.be/rB3_GO1QrSk",
    "https://tambien.github.io/Piano/audio/*",
    "https://play.howstuffworks.com/quiz/what-kind-of-cook-are-you",
    "https://games.engineering.com/Dynamic-Systems/*",
    "autograder-nchs.vercel.app",
    "https://player.vimeo.com/video/320513063/*",
    "https://player.vimeo.com/video/320333977/*",
    "https://player.vimeo.com/video/320334121/*",
    "https://player.vimeo.com/video/320334218/*",
    "https://player.vimeo.com/video/320334385/*",
    "https://player.vimeo.com/video/320516594/*",
    "https://vimeo.com/320513063/*",
    "https://vimeo.com/320333977/*",
    "https://vimeo.com/320334121/*",
    "https://vimeo.com/320334218/*",
    "https://vimeo.com/320334385/*",
    "https://vimeo.com/320516594/*",
    "edu.bandlab.com",
    "thegraphite.vercel.app",
    "https://sites.google.com/apps.nsd.org/orchestra-msnewman/home-2023*",
    "nchacks.vercel.app",
    "https://ia801902.us.archive.org/cors_get.php?path=/18/items/emularity_engine_v1/dosbox.json",
    "mutation.netlify.app",
    "biodiversity.netlify.app",
    "https://www.corefocusonmath.com/classrooms/login/index.php",
    "https://www.corefocusonmath.com/classrooms/lib/ajax/service.php*",
    "https://www.corefocusonmath.com/classrooms/theme/yui_combo.php*",
    "*login.live.com*",
    "*images.albertsons-media.com/is/*",
    "*api.app.prd.wendys.digital/web-client-gateway/*",
    "*neeal.fun/deep-sea*",
    "*neal.fun/deep-sea*",
    "*neal.fun/_nuxt/*",
    "*certiport.com*",
    "*pearson.com*",
    "*pearsonvue.com*",
    "*starttest.com*",
    "*starttest2.com*",
    "*startpractice.com*",
    "*programworkshop.com*",
    "*gettesting.com*",
    "*testnav.com*",
    "*pearsontestcontent.com*",
    "*chime.aws*",
    "*thawte.com*",
    "*usertrust.com*",
    "*comodoca.com*",
    "*cowriter.dev*",
    "*donjohnston.net*",
    "*cw-ws.qadji.com*",
    "*speechstream.net*",
    "*texthelp.com*",
    "*.cambiumtds.com",
    "*.cambiumast.com",
    "*safeyoutube.net*",
    "firewalledreplit.com",
    "*.firewalledreplit.com",
    "*.firewalledreplit.co",
    "*.cdn.replit.com",
    "cdn.replit.com",
  ];
  const blacklist = [
    "https://block.com/",
    "*coolmathgames.com*",
    "*www.hackertyper*",
    "https://3gpking.pro/",
    "https://3gpjizz.pro*",
    "*netflix.com*",
    "*spotify.com*",
    "*pandora.com*",
    "*music.youtube.com/*",
    "https://play.howstuffworks.com/*",
    "https://www.disneyplus.com/*",
    "http://invidious*",
    "https://soundcloud.com/*",
    "https://tubitv.com/*",
    "*www.heroku.com/*",
    "*heroku.com*",
    "https://sites.google.com/site/thegamecompilation/cookie-clicker-2",
    "https://sites.google.com/site/thegamecompilation/",
    "https://sites.google.com/site/thegamecompilation/*",
    "https://sites.google.com/site/tyronesgameshack/*",
    "http://github.com/binary-person/*",
    "https://trixter9994.github.io/Cookie-Clicker-Source-Code/",
    "*cookie-clicker*",
    "*cookieclicker*",
    "*//www.nydailynews.com/*",
    "https://www.dwservice.net/*",
    "https://slope--abnumality.repl.co/",
    "http://skribbl.io*",
    "http://www.purple.com/",
    "*.herokuapp.*",
    "*.heroku.*",
    "https://replit.com/@YPD/Website-Unblocker",
    "https://schedule-data-service.herokuapp.com/",
    "https://kodableapi.herokuapp.com",
    "https://github.com/QuiteAFancyEmerald/Holy-Unblocker",
    "https://github.com/QuiteAFancyEmerald*",
    "http://en.nickelodeonarabia.com/games/*",
    "https://yandex.com*",
    "*yandex.*",
    "*cbgamesdev*",
    "https://alloy-proxy.yoloswag3368.repl.co/",
    "*corrosion*repl.*",
    "*womginx*repl.*",
    "*ultraviolet*repl.*",
    "*thunkable.*",
    "*.openai.com*",
    "*openai.com*",
    "https://sites.google.com/view/castle-railroad/*",
    "*crosh*",
    "ia601500.us.archive.org",
    "ubg*.github.io",
    "kl0ningmachine3kloneh0.netlify.app",
    "*ubg*.github.io*",
    "*game*.github.*",
    "*netlify.app*",
    "https://www.symbaloo.com/mix/gamesbyblarkin?lang=EN",
    "https://www.bandlab.com/*/conversations/*",
    "*bandlab.com*",
    "*.xyz",
    "*ballbang*",
    "*bidoofery*",
    "*kanyeballshd*",
    "*lukicenturi*",
    "*qag99.*",
    "*tbg.*",
    "*therandombutton*",
    "*thetastypi*",
    "*tylerpalko*",
    "*teddblue*",
    "*github.com/*proxy*",
    "birdriver.org",
    "com.mx",
    "csb.app",
    "factoryballs.net",
    "jsfiddle.net",
    "luxurianthome.foundation",
    "medbury.com",
    "ononoki.org",
    "play2048.cc",
    "tiekoetter.com",
    "tree-board.net",
    "webglsamples.org",
    "workers.dev",
    "6kh0.github.io",
    "vercel.app",
    "*mrsmckeachiecomputerlab*",
    "https://sites.google.com/site/mostfungames69",
    "*porn*",
    "https://myactivity.google.com/delete-activity",
    "https://schoology.grades.repl.co/",
    "https://schoology.grades.repl.co/*",
    "https://padlet.com/gakivin605/home-schoology-qmnipdl5kbtkzl9e",
    "*.codesandbox.io",
    "*.dfsasfadesdf.repl.co",
    "*.elijahsocool.repl.co",
    "*.hop.sh",
    "*.pinkgithub1.repl.co",
    "*.spamz0.repl.co",
    "3v3ry0n3.*",
    "55gms.*",
    "algebraxyz.*",
    "blog1201.*",
    "buypass.*",
    "byvolp.*",
    "calc1208.*",
    "extrememath.*",
    "galacticnetwork.*",
    "jmw.*",
    "plungeproxy.*",
    "rhodium.*",
    "riptide.*",
    "scpwolf.*",
    "skyhax.*",
    "snorlaxs-cave*",
    "snorlaxscave.*",
    "whitespider.*",
    "womginx.*",
    "www.crazygames.*",
    "www.jordansmathwork.*",
    "www.weblfg.*",
    "xs.xenol.*",
    "zc.*",
    "https://docs.google.com/document/d/12c-SZwWbK52Xdf7mTd-EqDBR_mBY5lSlcMA8J3PlIqk/edit",
    "https://sites.google.com/*/pizza3x/*",
    "*pizzaedition*",
    "*babanagames*",
    "*schoolgames69*",
    "https://docs.google.com/document/d/1nK6tJb-sxfrrQJM9bSWcAV-Fo7jHasd_dWpj4VEVg5E/preview#heading=h.fcyllu4u32lu",
    "https://docs.google.com/document/d/1ebE4sCBR6u7B4xPfSPKt29IpgOpdv8L7oe-DRHiu9GE/edit",
    "*classroom69x*",
    "*classroom6x*",
    "*pizzalearns*",
    "*all-games*",
    "*popular-games*",
    "*classroom420x*",
    "*goofyclassroom1*",
    "*online-games*",
    "*googl-games*",
    "*populardoodlegames*",
    "*playarkadiumgames*",
    "*retro-bowl*",
    "https://www.rcsdk8.org/sites/main/files/file-attachments/homework_remembering_te_grade_4-1zwawpi.pdf",
    "https://docs.google.com/presentation/d/1kJ6K3SkgKeIv2et0EvII9f5CaTYTkaCK_MF84NALgQI/edit#slide=id.p",
    "https://docs.google.com/document/d/1zAwv9fhS64bAGeIJh9OSISANumzDrF2zCvlU0tI8f0s/edit#heading=h.3lsnabf6o5fn",
    "https://docs.google.com/presentation/d/1PqEaG0eIAE3LvZUxuXtis6KY61vLVJD0hAq_0K2X47c/edit#slide=id.g23cf6776ee2_0_161",
    "https://drive.google.com/drive/u/0/folders/1pCXaEjukH0NsTsSCb1F0hNbjs8_-LMXf",
    "https://drive.google.com/drive/u/0/folders/1VxjINYMDvvUSRKA_k2aJqq6JzmRQCI1s",
    "https://docs.google.com/document/d/1nK6tJb-sxfrrQJM9bSWcAV-Fo7jHasd_dWpj4VEVg5E/edit#heading=h.fcyllu4u32lu",
    "*unbl0ck*",
    "*11kNoONTNpSZeriWRAkPYnfnzsbjChrC1yv9o-kKgDz8*",
    "*greenstation*",
    "*schoolmessage*",
    "*cricket17*",
    "https://sites.google.com/olius/*",
    "*unblock*",
    "https://sites.google.com/d/1m3eSMYHlLdrY7uHVFlkEh5waY6jU7Xgw/p/1qmEv44CG6312zUNDQzrCLF0XGJiKg7X9/edit?pli=1",
    "*repl*.co*",
    "reddit.com",
  ];

  const host = new URL(url).hostname.toLowerCase().split(".");
  for (const item of whitelist) {
    if (item.match(/^([\w\d-]{1,63}\.)+[\w\d-]{1,63}$/i)) {
      const bits = item.toLowerCase().split(".");
      const works = bits.every((bit, index) => host.at(-1 - index) == bit);
      if (works) return "w";
    } else {
      const regex = new RegExp(
        "^" + item.replace(/[\]{}?^$().*\\+|[]/g, "\\$&").replace(/\\\*/g, ".*") + "$",
        "i",
      );
      if (regex.test(url)) return "w";
    }
  }
  for (const item of blacklist) {
    if (item.match(/^([\w\d-]{1,63}\.)+[\w\d-]{1,63}$/i)) {
      const bits = item.toLowerCase().split(".");
      const works = bits.every((bit, index) => host[index + (host.length - bits.length)] == bit);
      if (works) return "b";
    } else {
      const regex = new RegExp(
        "^" + item.replace(/[\]{}?^$().*\\+|[]/g, "\\$&").replace(/\\\*/g, ".*") + "$",
        "i",
      );
      if (regex.test(url)) return "b";
    }
  }

  return "u";
};
const processResults = async (
  query: string,
  data: { web: { results: { title: string; url: string; description: string }[] } },
) => {
  const preRanking: {
    title: string;
    url: string;
    description: string;
    domain: string;
    status: string;
  }[] = [];
  await Promise.all(
    data.web.results.map(async (result) => {
      const website = new URL(result.url).hostname;
      const websiteName =
        website == "news.ycombinator.com"
          ? "Hacker News"
          : website == "stackoverflow.com"
            ? "Stack Overflow"
            : website == "lightspeedsystems.com"
              ? "Lightspeed Systems"
              : website == "change.org"
                ? "Change.org"
                : website.replace(".co.uk", "").split(".").at(-2);

      preRanking.push({
        title: websiteName
          ? result.title.replace(new RegExp(`[-|·] ${websiteName}$`, "i"), "")
          : result.title,
        url: result.url,
        description: result.description,
        domain: website.replace(/^www\./, ""),
        status: checkBlocked(result.url),
      });
    }),
  );

  const usable = preRanking.filter((r) => r.status == "w" || r.status == "u");
  if (usable.length) {
    const r = await fetch("https://api.cohere.com/v1/rerank", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.COHERE_KEY!}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "rerank-english-v3.0",
        query,
        documents: usable.map(
          (r) => `${r.title}
${r.description}

by ${r.domain}`,
        ),
      }),
    });
    const json: { results: { index: number }[] } = await r.json();

    return json.results
      .map((r) => usable[r.index])
      .concat(preRanking.filter((r) => r.status == "b"));
  } else {
    return preRanking;
  }
};

const searchApi = async function (
  request: HttpRequest,
  context: InvocationContext,
): Promise<HttpResponse> {
  const q = request.query.get("q");
  if (!q) {
    return {
      status: 400,
      body: "Please provide a search query",
    };
  }

  const definitionPromise = fetchDefinition(q, process.env.GROQ_KEY!);

  const r = await fetch(
    "https://api.search.brave.com/res/v1/web/search?" +
      new URLSearchParams({ q, count: "10", result_filter: "web" }),
    {
      method: "GET",
      headers: {
        Accept: "application/json",
        "X-Subscription-Token": process.env.BRAVE_KEY!,
      },
    },
  );
  const results = await r.json();
  const processedResults = await processResults(q, results);

  const definition = await definitionPromise;

  return {
    body: JSON.stringify({
      results: processedResults,
      definition: definition,
    }),
  };
};

app.http("search", {
  methods: ["GET"],
  handler: searchApi,
});
